services:
  backend:
    container_name: core-template-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    restart: always

  worker:
    container_name: core-template-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always

  frontend:
    container_name: core-template-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
